### ISSUE TITLE
Restore CI testing for Python >= 3.8 or drop older Python versions?

### ISSUE THREAD

**Issue by mwtoews** [Deltares/xmipy#129]
CI testing for Python 3.8 and 3.9 was removed via f8792400f98d88ba9449cc9a7acc993bb3648042 even though this project should support [python>=3.8](https://github.com/Deltares/xmipy/blob/5d7c29052a2d2b1d6176e1af9b1c561173296e4b/pyproject.toml#L21). This lets breaking changes like #128 slip in. (The issue is only related to Python 3.8, and is a typing discrepancy related to `PathLike[Any]` vs `PathLike`). Some choices are:

1. Restore testing the minimum supported Python version in CI.yml, which will require fixing the typing issue. If fewer Python versions are desired, then test at least the oldest and newest supported versions, e.g. 3.8, 3.10, 3.12.
2. Or drop Python 3.8 since it will be dropped in October 2024 ([PEP 569](https://peps.python.org/pep-0569/)). This option should probably keep Python 3.9, as this will be around until October 2024 ([PEP 596], but it would need to be added to CI.yml.

I don't have any strong preference, so I'll let @Hofer-Julian weigh in.

**Comment by Hofer-Julian** [comment]
> I don't have any strong preference, so I'll let @Hofer-Julian weigh in.

So far I always supported the last three Python versions.
But you are right, we then should also update the minimum required Python version in the `pyproject.toml`
