### ISSUE TITLE
Tests fail on macOS

### ISSUE THREAD

**Issue by schwemro** [Deltares/xmipy#134]
The provided test suite fails with an OSError:

E           OSError: dlopen(/private/var/folders/k5/ngz7y_5x05z1f212lsh5zjhh0000gn/T/pytest-of-xxx/pytest-0/libmf6.dylib, 0x0006): tried: '/private/var/folders/k5/ngz7y_5x05z1f212lsh5zjhh0000gn/T/pytest-of-xxx/pytest-0/libmf6.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/k5/ngz7y_5x05z1f212lsh5zjhh0000gn/T/pytest-of-xxx/pytest-0/libmf6.dylib' (no such file), '/private/var/folders/k5/ngz7y_5x05z1f212lsh5zjhh0000gn/T/pytest-of-xxx/pytest-0/libmf6.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

System and hardware properties:

Machine type: arm64
Processor type: arm
Platform type: macOS-13.6.6-arm64-arm-64bit
Operating system: Darwin
Operating system release: 22.6.0
Operating system version: Darwin Kernel Version 22.6.0: Mon Feb 19 19:43:13 PST 2024;

**Comment by mjr-deltares** [comment]
Hi @schwemro, thanks for reporting this back to us. I will have a look into your issue and get back to you.

**Comment by jdhughes-dev** [comment]
There is a statically built version for Mac arm chips (`macarm.zip`) that should solve your issue.

[https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases](https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases)

If this does not work, you will have to compile from source locally.
