### ISSUE TITLE
implement `update_until`

### ISSUE THREAD

**Issue by visr** [Deltares/xmipy#92]
It is currently marked as `NotImplemented`:

https://github.com/Deltares/xmipy/blob/a92cabf09599c0cca35ae1a3e2105a6797ec17da/xmipy/xmiwrapper.py#L140-L141

Since Ribasim currently typically uses adaptive timesteppers, `update_until` makes more sense to use than `update`.

https://github.com/Deltares/Ribasim/blob/3677e2c283f246a0cdd6db0ea447964aa2453d8c/core/src/bmi.jl#L64-L76

**Comment by mjr-deltares** [comment]
Hey @visr this went in with #94
